### ISSUE TITLE
Framework kiezen

### ISSUE THREAD

**Issue by yaron** [ChristmasTop100/frontend-2016#1]

**Comment by dylancom** [comment]
React 👍

**Comment by yaron** [comment]
Ok, hoe beginnen we? Een starter kit of gewoon een index.html met react uit een cdn?

**Comment by dylancom** [comment]
https://github.com/facebookincubator/create-react-app

Dit is tegenwoordig de standaard starter-kit.
Kan ik al iets pushen naar frontend-2016? Heb nu een basic setup + vallend sneeuw.
Morgen kijken of ik data kan fetchen met GraphQL

**Comment by yaron** [comment]
ja als het goed is kan je dingen pushen, is nog een volledig lege repo.
Heb voor de backend trouwens ook de link van votes terug naar users en songs werkend, die zal ik vanavond nog op prod zetten dan kan je dat ook gebruiken.

**Comment by yaron** [comment]
Ik heb een overzicht gemaakt van het graphql schema, zal het updaten als er dingen veranderen:
https://github.com/ChristmasTop100/backend-2016/wiki/GraphQL-schema
