### ISSUE TITLE
Frontpage/songs overview

### ISSUE THREAD

**Issue by yaron** [ChristmasTop100/frontend-2016#2]
Overzichtpagina met alle nummers en huidige stemmen van huidige gebruiker.

**Comment by dylancom** [comment]
Play button laadt nu de iframe met het juiste nummer maar bevat geen autoplay. 
Dit is op het moment niet mogelijk met de Spotify Play embed button.
Misschien kunnen we automatisch een click triggeren o.i.d.?

**Comment by dylancom** [comment]
# Autoplay
## Is there an auto-play option on the widget?

No, there is not. The user has to start playback by clicking on the Play Button, which will open the web player or desktop client to start the playback.

**Comment by dylancom** [comment]
@yaron Ik heb zojuist de performance van de vote buttons verbeterd. 
(HTML buttons gebruikt i.p.v. Material Components)
Daarnaast kan je nu alleen een vote tussen 0 & 20 uitbrengen en heb ik ook een timeout van 500ms toegevoegd. (Die zich elke keer cleared op het moment dat je een button klikt)
Daar kan straks dus de API call om de votes te updaten in.

**Comment by yaron** [comment]
Mocht er iemand nog tijd over hebben: Counter met nog te geven punten (start bij 100, telt af bij iedere gegeven punt) Kan denk ik naast spotify player in de balk, dan blijft hij ook mooi sticky.

**Comment by robindrost** [comment]
Fixed.
