### ISSUE TITLE
Logins

### ISSUE THREAD

**Issue by yaron** [ChristmasTop100/frontend-2016#4]
Back end will support logins with graphQL and JSON web tokens.

**Comment by yaron** [comment]
Lijkt goed te werken, alleen nog even kijken of sessies ook persistent kunnen zijn door de JWT in local storage/cookie/... op te slaan en uit te lezen bij opnieuw laden van de pagina.

**Comment by yaron** [comment]
Lekker bezig Dylan. Ik zie alleen nog dat ik uitgelogd wordt na een refresh als ik via de one time login ben ingelogd. Heb ik iets verkeerd gecopy/paste of ben je vergeten een aanpassing ook daar door te voeren?

**Comment by robindrost** [comment]
Fixed
